# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Calculator2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(553, 627)
        Form.setStyleSheet("background-color: rgb(243, 244, 255);")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(20, 0, 471, 51))
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\";\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(140, 60, 271, 321))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_plus = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_plus.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_plus.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_plus.setStyleSheet("QPushButton {\n"
"    width: 89px;\n"
"    height: 89px;\n"
"    background-color: #ffca4c;\n"
"    color: rgb(0, 0, 0);\n"
"    font: 87 24pt \"Arial\";\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ff8e2b;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #ff7627;\n"
"}")
        self.pushButton_plus.setObjectName("pushButton_plus")
        self.gridLayout.addWidget(self.pushButton_plus, 3, 3, 1, 1)
        self.pushButton_ravno = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_ravno.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_ravno.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_ravno.setStyleSheet("QPushButton {\n"
"    width: 89px;\n"
"    height: 89px;\n"
"    background-color: #ffca4c;\n"
"    color: rgb(0, 0, 0);\n"
"    font: 87 24pt \"Arial\";\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ff8e2b;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #ff7627;\n"
"}")
        self.pushButton_ravno.setObjectName("pushButton_ravno")
        self.gridLayout.addWidget(self.pushButton_ravno, 4, 3, 1, 1)
        self.pushButton_minus = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_minus.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_minus.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_minus.setStyleSheet("QPushButton {\n"
"    width: 89px;\n"
"    height: 89px;\n"
"    background-color: #ffca4c;\n"
"    color: rgb(0, 0, 0);\n"
"    font: 87 24pt \"Arial\";\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ff8e2b;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #ff7627;\n"
"}")
        self.pushButton_minus.setObjectName("pushButton_minus")
        self.gridLayout.addWidget(self.pushButton_minus, 2, 3, 1, 1)
        self.pushButton_percent = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_percent.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_percent.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_percent.setStyleSheet("QPushButton {\n"
"    width: 89px;\n"
"    height: 89px;\n"
"    background-color: #ffca4c;\n"
"    color: rgb(0, 0, 0);\n"
"    font: 87 24pt \"Arial\";\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ff8e2b;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #ff7627;\n"
"}")
        self.pushButton_percent.setObjectName("pushButton_percent")
        self.gridLayout.addWidget(self.pushButton_percent, 0, 2, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_9.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"    width: 89px;\n"
"    height: 89px;\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    font: 87 24pt \"Arial\";\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #bce8ff;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #6f91ff;\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 1, 2, 1, 1)
        self.pushButton_umnozh = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_umnozh.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_umnozh.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_umnozh.setStyleSheet("QPushButton {\n"
"    width: 89px;\n"
"    height: 89px;\n"
"    background-color: #ffca4c;\n"
"    color: rgb(0, 0, 0);\n"
"    font: 87 24pt \"Arial\";\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ff8e2b;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #ff7627;\n"
"}")
        self.pushButton_umnozh.setObjectName("pushButton_umnozh")
        self.gridLayout.addWidget(self.pushButton_umnozh, 1, 3, 1, 1)
        self.pushButton_tochka = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_tochka.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_tochka.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_tochka.setStyleSheet("QPushButton {\n"
"    width: 89px;\n"
"    height: 89px;\n"
"    background-color: #ffca4c;\n"
"    color: rgb(0, 0, 0);\n"
"    font: 87 24pt \"Arial\";\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ff8e2b;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #ff7627;\n"
"}")
        self.pushButton_tochka.setObjectName("pushButton_tochka")
        self.gridLayout.addWidget(self.pushButton_tochka, 4, 2, 1, 1)
        self.pushButton_delenie = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_delenie.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_delenie.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_delenie.setStyleSheet("QPushButton {\n"
"    width: 89px;\n"
"    height: 89px;\n"
"    background-color: #ffca4c;\n"
"    color: rgb(0, 0, 0);\n"
"    font: 87 24pt \"Arial\";\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ff8e2b;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #ff7627;\n"
"}")
        self.pushButton_delenie.setObjectName("pushButton_delenie")
        self.gridLayout.addWidget(self.pushButton_delenie, 0, 3, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_6.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    width: 89px;\n"
"    height: 89px;\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    font: 87 24pt \"Arial\";\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #bce8ff;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #6f91ff;\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 2, 2, 1, 1)
        self.pushButton_del = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_del.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_del.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_del.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_del.setStyleSheet("QPushButton {\n"
"    width: 89px;\n"
"    height: 89px;\n"
"    background-color: #ffca4c;\n"
"    color: rgb(0, 0, 0);\n"
"    font: 87 24pt \"Arial\";\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ff8e2b;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #ff7627;\n"
"}")
        self.pushButton_del.setObjectName("pushButton_del")
        self.gridLayout.addWidget(self.pushButton_del, 0, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_3.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    width: 89px;\n"
"    height: 89px;\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    font: 87 24pt \"Arial\";\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #bce8ff;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #6f91ff;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 3, 2, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_7.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    width: 89px;\n"
"    height: 89px;\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    font: 87 24pt \"Arial\";\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #bce8ff;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #6f91ff;\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    width: 89px;\n"
"    height: 89px;\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    font: 87 24pt \"Arial\";\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #bce8ff;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #6f91ff;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 3, 1, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_8.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"    width: 89px;\n"
"    height: 89px;\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    font: 87 24pt \"Arial\";\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #bce8ff;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #6f91ff;\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 1, 1, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_5.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    width: 89px;\n"
"    height: 89px;\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    font: 87 24pt \"Arial\";\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #bce8ff;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #6f91ff;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 2, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_4.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    width: 89px;\n"
"    height: 89px;\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    font: 87 24pt \"Arial\";\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #bce8ff;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #6f91ff;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 2, 0, 1, 1)
        self.pushButton_0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_0.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_0.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_0.setStyleSheet("QPushButton {\n"
"    width: 89px;\n"
"    height: 89px;\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    font: 87 24pt \"Arial\";\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #bce8ff;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #6f91ff;\n"
"}")
        self.pushButton_0.setObjectName("pushButton_0")
        self.gridLayout.addWidget(self.pushButton_0, 4, 1, 1, 1)
        self.pushButton_nazad = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_nazad.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_nazad.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_nazad.setStyleSheet("QPushButton {\n"
"    width: 89px;\n"
"    height: 89px;\n"
"    background-color: #ffca4c;\n"
"    color: rgb(0, 0, 0);\n"
"    font: 87 24pt \"Arial\";\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ff8e2b;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #ff7627;\n"
"}")
        self.pushButton_nazad.setObjectName("pushButton_nazad")
        self.gridLayout.addWidget(self.pushButton_nazad, 0, 0, 1, 1)
        self.pushButton_voskl = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_voskl.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_voskl.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_voskl.setStyleSheet("QPushButton {\n"
"    width: 89px;\n"
"    height: 89px;\n"
"    background-color: #ffca4c;\n"
"    color: rgb(0, 0, 0);\n"
"    font: 87 24pt \"Arial\";\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ff8e2b;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #ff7627;\n"
"}")
        self.pushButton_voskl.setObjectName("pushButton_voskl")
        self.gridLayout.addWidget(self.pushButton_voskl, 4, 0, 1, 1)
        self.pushButton_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_1.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_1.setStyleSheet("QPushButton {\n"
"    width: 89px;\n"
"    height: 89px;\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    font: 87 24pt \"Arial\";\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #bce8ff;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #6f91ff;\n"
"}")
        self.pushButton_1.setObjectName("pushButton_1")
        self.gridLayout.addWidget(self.pushButton_1, 3, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(80, 60, 61, 321))
        self.gridLayoutWidget_2.setStyleSheet("QPushButton {\n"
"    width: 89px;\n"
"    height: 89px;\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    font: 87 24pt \"Arial\";\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #bce8ff;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #6f91ff;\n"
"}")
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_ln = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_ln.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_ln.setStyleSheet("QPushButton {\n"
"    width: 89px;\n"
"    height: 89px;\n"
"    background-color:#ffa2a2;\n"
"    color: rgb(0, 0, 0);\n"
"    font: 87 24pt \"Arial\";\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ff6f5c;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #ff0800;\n"
"}")
        self.pushButton_ln.setObjectName("pushButton_ln")
        self.gridLayout_2.addWidget(self.pushButton_ln, 3, 0, 1, 1)
        self.pushButton_cos = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_cos.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_cos.setStyleSheet("QPushButton {\n"
"    width: 89px;\n"
"    height: 89px;\n"
"    background-color:#ffa2a2;\n"
"    color: rgb(0, 0, 0);\n"
"    font: 87 24pt \"Arial\";\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ff6f5c;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #ff0800;\n"
"}")
        self.pushButton_cos.setObjectName("pushButton_cos")
        self.gridLayout_2.addWidget(self.pushButton_cos, 1, 0, 1, 1)
        self.pushButton_tg = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_tg.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_tg.setStyleSheet("QPushButton {\n"
"    width: 89px;\n"
"    height: 89px;\n"
"    background-color:#ffa2a2;\n"
"    color: rgb(0, 0, 0);\n"
"    font: 87 24pt \"Arial\";\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ff6f5c;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #ff0800;\n"
"}")
        self.pushButton_tg.setObjectName("pushButton_tg")
        self.gridLayout_2.addWidget(self.pushButton_tg, 2, 0, 1, 1)
        self.pushButton_delx = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_delx.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_delx.setStyleSheet("QPushButton {\n"
"    width: 89px;\n"
"    height: 89px;\n"
"    background-color:#ffa2a2;\n"
"    color: rgb(0, 0, 0);\n"
"    font: 87 24pt \"Arial\";\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ff6f5c;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #ff0800;\n"
"}")
        self.pushButton_delx.setObjectName("pushButton_delx")
        self.gridLayout_2.addWidget(self.pushButton_delx, 4, 0, 1, 1)
        self.pushButton_sin = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_sin.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_sin.setStyleSheet("QPushButton {\n"
"    width: 89px;\n"
"    height: 89px;\n"
"    background-color:#ffa2a2;\n"
"    color: rgb(0, 0, 0);\n"
"    font: 87 24pt \"Arial\";\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ff6f5c;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #ff0800;\n"
"}")
        self.pushButton_sin.setObjectName("pushButton_sin")
        self.gridLayout_2.addWidget(self.pushButton_sin, 0, 0, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(70, 380, 341, 71))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_14 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_14.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_14.setStyleSheet("QPushButton {\n"
"    width: 89px;\n"
"    height: 89px;\n"
"    background-color: black;\n"
"    color: white;\n"
"    font: 87 10pt \"Arial\";\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:  black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  black;\n"
"}")
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_3.addWidget(self.pushButton_14, 0, 2, 1, 1)
        self.pushButton_sqrt = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_sqrt.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_sqrt.setStyleSheet("QPushButton {\n"
"    width: 89px;\n"
"    height: 89px;\n"
"    background-color:#ffa2a2;\n"
"    color: rgb(0, 0, 0);\n"
"    font: 87 24pt \"Arial\";\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ff6f5c;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #ff0800;\n"
"}")
        self.pushButton_sqrt.setObjectName("pushButton_sqrt")
        self.gridLayout_3.addWidget(self.pushButton_sqrt, 0, 1, 1, 1)
        self.pushButton_step2 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_step2.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_step2.setStyleSheet("QPushButton {\n"
"    width: 89px;\n"
"    height: 89px;\n"
"    background-color:#ffa2a2;\n"
"    color: rgb(0, 0, 0);\n"
"    font: 87 24pt \"Arial\";\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ff6f5c;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #ff0800;\n"
"}")
        self.pushButton_step2.setObjectName("pushButton_step2")
        self.gridLayout_3.addWidget(self.pushButton_step2, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Calculator"))
        self.pushButton_plus.setText(_translate("Form", "+"))
        self.pushButton_ravno.setText(_translate("Form", "="))
        self.pushButton_minus.setText(_translate("Form", "-"))
        self.pushButton_percent.setText(_translate("Form", "%"))
        self.pushButton_9.setText(_translate("Form", "9"))
        self.pushButton_umnozh.setText(_translate("Form", "x"))
        self.pushButton_tochka.setText(_translate("Form", "."))
        self.pushButton_delenie.setText(_translate("Form", "/"))
        self.pushButton_6.setText(_translate("Form", "6"))
        self.pushButton_del.setText(_translate("Form", "DEL"))
        self.pushButton_3.setText(_translate("Form", "3"))
        self.pushButton_7.setText(_translate("Form", "7"))
        self.pushButton_2.setText(_translate("Form", "2"))
        self.pushButton_8.setText(_translate("Form", "8"))
        self.pushButton_5.setText(_translate("Form", "5"))
        self.pushButton_4.setText(_translate("Form", "4"))
        self.pushButton_0.setText(_translate("Form", "0"))
        self.pushButton_nazad.setText(_translate("Form", "<-"))
        self.pushButton_voskl.setText(_translate("Form", "!"))
        self.pushButton_1.setText(_translate("Form", "1"))
        self.pushButton_ln.setText(_translate("Form", "Ln"))
        self.pushButton_cos.setText(_translate("Form", "Cos"))
        self.pushButton_tg.setText(_translate("Form", "Tg"))
        self.pushButton_delx.setText(_translate("Form", "1/x"))
        self.pushButton_sin.setText(_translate("Form", "Sin"))
        self.pushButton_14.setText(_translate("Form", "Выкл"))
        self.pushButton_sqrt.setText(_translate("Form", "Sqrt"))
        self.pushButton_step2.setText(_translate("Form", "^2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
